### ISSUE TITLE
Set extensionKind in package.json to support Remote Development

### ISSUE THREAD

**Issue by mjbvz** [CoenraadS/Bracket-Pair-Colorizer-2#108]
Hi, I'm on the VS Code team. We recently released support for [Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) and I noticed that your may extension need a small change to ensure users have a good experience when using it remote workspaces.

## What is the issue?
To make remote development as transparent as possible to users, VS Code distinguishes two classes of extensions:

- **UI Extensions**: These extensions make contributions to the VS Code user interface and are always run on the user's local machine. UI Extensions cannot directly access files in the workspace, or run scripts/tools installed in that workspace or on the machine. Example UI Extensions include: themes, snippets, language grammars, and keymaps.

- **Workspace Extensions**: These extensions are run on the same machine as where the workspace is located. When in a local workspace, Workspace Extensions are run on the local machine. When in a remote workspace, Workspace Extensions are run on the remote machine. Workspace Extensions can access files in the workspace to provide rich, multi-file language services, debugger support, or perform complex operations on multiple files in workspace (either themselves or by invoking scripts/tools). 

You can find more details about this architecture [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types).

**VS Code currently infers that your extension is a Workspace Extension. This means that users who have your extension installed must also install it to the remote in order to use it in remote workspaces.** I believe that your extension should probably be a UI extension instead. That way your extension will always be enabled for users who install it, even if they open a remote workspace.

## How do I fix this?
To tell VS Code that your extension is a UI extension, just add [`"extensionKind": "ui"`](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) to your extension's package.json.

UI Extensions always run on the user's local machine, even when they open a remote workspace. 

I'll submit a PR that does this. Please let me know if you have any questions or concerns about the issue. We've also put together [a guide](https://code.visualstudio.com/api/advanced-topics/remote-extensions#testing-and-debugging-your-extension) to help you test your extension in remote workspaces

*PS: As a temporary workaround for a few popular extensions, we've automatically added your extension to an internal whitelist so that is always treated as a UI extension*

**Comment by vimota** [comment]
Any updates on this? Would be great to be able to run this on VSCode Remote! :)

**Comment by davefollett** [comment]
I read it that way originally too.  But it does work already because the VS Code team put this extension on a UI white-list.  Just make sure to install it on the local side, not he remote side.

Still would be nice to get this merged in though.

**Comment by vimota** [comment]
Hmm I don't see an option to install it locally:
![image](https://user-images.githubusercontent.com/865701/59942596-fad48800-9414-11e9-8d03-3d27f4b69e45.png)

But I got it to work finally by adding to my settings:
`"remote.extensionKind": {
        "coenraads.bracket-pair-colorizer-2": "ui"
    }`

**Comment by SimchaWood** [comment]
> But I got it to work finally by adding to my settings:
> `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }`

I was able to get it to work with local files after doing this, but it still does not work with files in remote workspaces.

**Comment by davefollett** [comment]
@vimota I had to open a 2nd VS Code that was not connected to a Remote Workspace.  Then I could install it locally.

**Comment by qneverless** [comment]
Works for me on both remote and local files. Installed locally and added
` "remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` to remote settings file.

**Comment by XuehaiPan** [comment]
It works for me. Just add `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` to settings.json. Add it to local setting file can also work.
![Screenshot from 2019-07-22 20-36-26](https://user-images.githubusercontent.com/16078332/61633236-3e930980-acc1-11e9-9eb8-701045c56712.png)

**Comment by mjmr89** [comment]
> It works for me. Just add `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` to settings.json. Add it to local setting file can also work.
> ![Screenshot from 2019-07-22 20-36-26](https://user-images.githubusercontent.com/16078332/61633236-3e930980-acc1-11e9-9eb8-701045c56712.png)

Unfortunately this isn't working for me - tried putting it in all three settings files - user, the remote server, and the workspace settings. Works great when on my local computer, just not when I'm remoting into another server.

**Comment by XuehaiPan** [comment]
> > It works for me. Just add `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` to settings.json. Add it to local setting file can also work.
> > ![Screenshot from 2019-07-22 20-36-26](https://user-images.githubusercontent.com/16078332/61633236-3e930980-acc1-11e9-9eb8-701045c56712.png)
> 
> Unfortunately this isn't working for me - tried putting it in all three settings files - user, the remote server, and the workspace settings. Works great when on my local computer, just not when I'm remoting into another server.

Uninstall the extension on the remote machine and install it on the local one, then reload the window.

**Comment by davidban77** [comment]
Hi @XuehaiPan I am in the same situation as @mjmr89 , I am testing it on a Dev Container and added the `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` into the remote server settings and is not working. The extension is not installed on the container either.

Wondering if somebody made it to work on a container environment.

**Comment by XuehaiPan** [comment]
1. add "remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" } to settings.json.
2. uninstall the extension on the remote (SSH/WSL/Container).
3. install the extension and enable it locally.
4. reload window.

Remote - SSH:
![Screenshot from 2019-07-22 20-36-26](https://user-images.githubusercontent.com/16078332/61633236-3e930980-acc1-11e9-9eb8-701045c56712.png)

Remote - Containers:
![Screen Shot 2019-07-25 at 20 38 06](https://user-images.githubusercontent.com/16078332/61876578-c8401280-af1f-11e9-8cad-5261444d2f08.png)

Remote - WSL:
![Screen Shot 2019-07-25 at 20 58 31](https://user-images.githubusercontent.com/16078332/61876627-e9086800-af1f-11e9-913b-d0b3b8787164.png)

**Comment by SimchaWood** [comment]
This still does not work for me when using Remote-SSH. 

I've done the following:
1) Add remote.extensionKind to settings.json:
![extensionKind](https://user-images.githubusercontent.com/31593126/61880708-5e921b00-aec3-11e9-807e-f7d81cc94f79.png)

2) Ensured that the extension is installed locally and not on the remote server (I checked the .vscode-server/extensions folder as well):
![localInstalled](https://user-images.githubusercontent.com/31593126/61880824-94370400-aec3-11e9-9998-d81a0e6ecff9.png)

3) Reload window.

When I am _not_ connected to the remote server the extension works fine:
![doesWork](https://user-images.githubusercontent.com/31593126/61881085-04de2080-aec4-11e9-92e6-6e5a150e78ff.png)

When I am connected to the remote server the extension does not work for local or remote files:
![doesntWork](https://user-images.githubusercontent.com/31593126/61881145-1c1d0e00-aec4-11e9-96d9-6194b002a306.png)

**Comment by davidban77** [comment]
Hi @XuehaiPan did those exact steps and no luck. But from your pics you are *[attached](https://code.visualstudio.com/docs/remote/containers#_attaching-to-running-containers)* to the container correct? I am using it as a [full-development environment](https://code.visualstudio.com/docs/remote/containers#_creating-a-devcontainerjson-file) and not sure if there is a difference in the environment to make it behave differently.

**Comment by davidban77** [comment]
version 1 works though

**Comment by mjmr89** [comment]
I've followed the instructions, but with no luck. Though the extension *is* still working on non-remote clients still.

**Comment by XuehaiPan** [comment]
I have tested on a new installation machine (Windows 10 Version 1903). The extension worked nicely on remote SSH/WSL/Container.

the extension works well for me on:

|                                 | version                                                     |
| :-----------------------------: | :---------------------------------------------------------- |
|             VS Code             | latest stable version (1.36.1)                              |
| Bracket Pair Colorizer 2 (Beta) | latest version (0.0.28)                                     |
|               OS                | Ubuntu 18.04.2 LTS / macOS Mojave / Windows 10 Version 1903 |
|           SSH Machine           | Ubuntu 16.04 LTS / Ubuntu 18.04.2 LTS                       |
|           WSL Machine           | Ubuntu 18.04.2 LTS                                          |
|          Docker Image           | ubuntu:18.04                                                |

```jsonc
// settings.json (USER)

{
    //* Bracket Pair Colorizer */
    "bracket-pair-colorizer-2.colorMode": "Consecutive", // default value
    "bracket-pair-colorizer-2.colors": [
        "Gold",
        "DeepPink",
        "Cyan",
        "DarkOrange",
        "LimeGreen",
        "Magenta",
        "DeepSkyBlue",
        "HotPink",
        "LightSeaGreen",
        "Orchid"
    ],
    "bracket-pair-colorizer-2.showBracketsInGutter": true,
    "bracket-pair-colorizer-2.showBracketsInRuler": true,
    "bracket-pair-colorizer-2.showHorizontalScopeLine": true, // default value
    "bracket-pair-colorizer-2.showVerticalScopeLine": true, // default value
    "bracket-pair-colorizer-2.highlightActiveScope": true,

    //* Remote */
    "remote.extensionKind": {
        "coenraads.bracket-pair-colorizer-2": "ui"
    },
    "remote.SSH.defaultExtensions": [
        "ms-python.anaconda-extension-pack",
        "ms-ceintl.vscode-language-pack-zh-hans",
        "formulahendry.code-runner",
        "donjayamanne.githistory",
        "eamodio.gitlens",
        "ryu1kn.partial-diff",
        "christian-kohler.path-intellisense",
        "ms-python.python"
    ],
}
```

test code:

```Cpp
// test.cpp

int main()
{
    int *a;
    {{{{{{{{{{}}}}}}}}}}
    a[a[a[a[a[a[a[a[a[a[0]]]]]]]]]];
    ((((((((((0))))))))));
    return 0;
}
```

<img width="467" alt="Screen Shot 2019-07-26 at 14 59 08" src="https://user-images.githubusercontent.com/16078332/61932420-f4a66e00-afb5-11e9-894e-3475c5d11bf8.png">

**Comment by XuehaiPan** [comment]
The extension works well for me on remote SSH/WSL/Container for C++. But it failed to colorize python scripts. It might be a language specific error.

<img width="737" alt="Screen Shot 2019-07-26 at 15 13 12" src="https://user-images.githubusercontent.com/16078332/61933478-8f07b100-afb8-11e9-93b1-49347f984717.png">

**Comment by Mark-L6n** [comment]
For me, in the extensions list, Bracket Pair Colorizer 2 has an `install on SSH..` button.  After clicking it, I can see it on the remote machine  in `~/.vscode-server/extensions/`.
But strangely, it still does not work in remote python or javascript files.
Tried adding  `"remote.extensionKind": { "coenraads.bracket-pair-colorizer-2": "ui" }` to remote `~/.vscode/settings.json`.  Unsurprisingly, that didn't work either, since it already was able to install files on the remote machine.

**Comment by ironbishop** [comment]
Like XuehaiPan, I have this issue only on Python files. (after I set `remote.extensionKind`).

**Comment by attempted** [comment]
Same here; definitely language specific. For now I've installed the the first version since I mostly use Python.

**Comment by marcinz** [comment]
I also see that colorization is not working in Python files. Has anyone figured that out?

**Comment by mjmr89** [comment]
I somehow fixed the issue for a couple months, but my computer died and I've had to start over - and now, of course, I have this issue again. Not sure why its been so long and there is barely a sometimes-working solution. But I actually don't have this on python only files, I have it on json & vue files at least as well. Of course I've changed the settings file as talked about, the extension is only on the local computer, etc.

**Comment by parkerault** [comment]
I'm having the same issue on WSL. I tried all of the workarounds above and none of them worked.
```
Name: Bracket Pair Colorizer 2
Id: coenraads.bracket-pair-colorizer-2
Description: A customizable extension for colorizing matching brackets
Version: 0.0.28
Publisher: CoenraadS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
```
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by egamma** [comment]
The fact the extension does not colorize JSON and Python files in the remote case are upstream VS Code issues that we will address. Pls see https://github.com/microsoft/vscode/issues/88837 https://github.com/microsoft/vscode/issues/88835

**Comment by matheust3** [comment]
Not working on Dart files

**Comment by astroboylrx** [comment]
Same here. The workaround does not work for LaTeX files. If it is language specific, where can we set the language-binding?
