### ISSUE TITLE
Highlighting LaTeX with LaTeXWorkshop not working

### ISSUE THREAD

**Issue by sloth3toe** [CoenraadS/Bracket-Pair-Colorizer-2#11]
LaTeXWorkshop now provides more syntax for brackets in v5.10.2 (https://github.com/James-Yu/LaTeX-Workshop/issues/803). The feature was specifically requested so that LaTeX can work with Bracket=Pair-Colorizer-2 since it doesn't with Bracket-Pair inside math mode (https://github.com/CoenraadS/BracketPair/issues/132).

I tried adding the following to `settings.json` but nothing changes (no brackets are colored). I made sure it works for the pre-defined languages.

Any idea what may be going on?

```
    "bracket-pair-colorizer-2.language-overrides": [
        {
            "language": "latex",
            "scopes": [
                {
                    "open": "punctuation.math.begin.bracket.curly",
                    "close": "punctuation.math.end.bracket.curly"
                },
                {
                    "open": "punctuation.math.begin.bracket.round",
                    "close": "punctuation.math.end.bracket.round"
                },
                {
                    "open": "punctuation.definition.brackets.tex"
                }
            ]
        }
    ]
```

**Comment by sloth3toe** [comment]
This could be a general issue outside of LaTeXWorkshop.

I tried for Matlab defining pairs for Matlab (syntax highlight by https://github.com/Gimly/vscode-matlab) as well, with no success:

```
    "bracket-pair-colorizer-2.language-overrides": [
        {
            "language": "latex",
            "scopes": [
                {
                    "open": "punctuation.math.begin.bracket.curly",
                    "close": "punctuation.math.end.bracket.curly"
                },
                {
                    "open": "punctuation.math.begin.bracket.round",
                    "close": "punctuation.math.end.bracket.round"
                },
                {
                    "open": "punctuation.definition.brackets.tex"
                }
            ]
        },
        {
            "language": "matlab",
            "scopes": [
                {
                    "open": "meta.parens.matlab"
                },
                {
                    "open": "meta.brackets.matlab"
                },
                {
                    "open": "meta.brackets.curly.matlab"
                }
            ]
        }
    ]
```

**Comment by CoenraadS** [comment]
A lot of languages are broken atm, I'm reworking (again) the bracket parsing logic and will see if I can get it to work for LaTeX also.

**Comment by CoenraadS** [comment]
Does 0.0.17 help?

![image](https://user-images.githubusercontent.com/5593825/46164691-f5378080-c28e-11e8-82ae-a8b9c12e9151.png)


I didn't try the maths stuff

**Comment by sloth3toe** [comment]
Yes it works! For the math stuff as well!

But it looks like we no longer have to define the language scopes ourselves anymore? (maybe that's easier when there are many many types of scopes for the same language)

**Comment by sloth3toe** [comment]
I notice that this works even for brackets with no special scopes (not all of them are always defined using the LaTeX Workshop extension) so it's actually great news. At the same time I'm not sure how it works with extending to new languages.

**Comment by CoenraadS** [comment]
I will get it right eventually 😅

**Comment by sloth3toe** [comment]
Actually, it looks like there was just some glitch. It must have been that I typed more content, and somehow the coloring didn't get updated and so the spots that were highlighted are no longer the right ones. But after a while it's now back to normal.

So, either a glitch or it's a bit slow at times?

**Comment by CoenraadS** [comment]
In V1 I would just color the whole document every time which prevented
these errors. Now I try to be more smart and cache line-state, but its very
likely I don't invalidate lines properly.

**Comment by CoenraadS** [comment]
I will close this issue, if you experience coloring problems please open a new one 👍
