### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by adriancubillos** [CoenraadS/Bracket-Pair-Colorizer-2#112]
- Issue Type: `Performance`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.0.28`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/adrian/CoenraadS.bracket-pair-colorizer-2-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by aravindvnair99** [comment]
Duplicate of #55. Please close this and post there instead.

@adriancubillos

**Comment by adriancubillos** [comment]
Closing as per request. Issue seems to be being tracked already.

**Comment by adriancubillos** [comment]
Closing.
