### ISSUE TITLE
not working on remote-ssh

### ISSUE THREAD

**Issue by xspeed1989** [CoenraadS/Bracket-Pair-Colorizer-2#129]
i install this on remote-ssh, but it does not working

**Comment by chandr3sh** [comment]
I had the same issue. It is not working on WSL as well.
VS Code - Insiders suggest to install it on remote machine (WSL in my case),

**Comment by falkben** [comment]
Not really a solution, but version 1 Bracket Pair Colorizer works on WSL (probably also remote-ssh):

> Name: Bracket Pair Colorizer
> Id: coenraads.bracket-pair-colorizer
> Description: A customizable extension for colorizing matching brackets
> Version: 1.0.61
> Publisher: CoenraadS
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

**Comment by xspeed1989** [comment]
> Not really a solution, but version 1 Bracket Pair Colorizer works on WSL (probably also remote-ssh):
> 
> > Name: Bracket Pair Colorizer
> > Id: coenraads.bracket-pair-colorizer
> > Description: A customizable extension for colorizing matching brackets
> > Version: 1.0.61
> > Publisher: CoenraadS
> > VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer
install the ext on local is a right way !
