### ISSUE TITLE
Need more parse line. (It limited 5000 line)

### ISSUE THREAD

**Issue by azenapow** [CoenraadS/Bracket-Pair-Colorizer-2#168]
Bracket Pair Colorizer 1.0.61
Version: 1.39.0-insider (user setup)
OS: Windows_NT x64 10.0.18362

I have very long C++ source files. (over 10000 lines)
BPC can only parse 5000 lines.
Can I parse more?
Please add user setting for modification.

**Comment by diggit** [comment]
You are reporting limitation of **version 1**. V2 highlights even long files. Unfortunately, it has performance issues. (#184)

**Comment by azenapow** [comment]
Thanks. but V2 has critical crash under Remote Development Environment.
