### ISSUE TITLE
[feature-request] deactivate color globally and color bracket based on theme

### ISSUE THREAD

**Issue by GammaGames** [CoenraadS/Bracket-Pair-Colorizer-2#23]
I like the way my theme has the brackets set up, what I really want to use the extension for is to highlight my current scope and show the brackets in the gutter. With the following settings, I can mostly achieve that:

```json
    "bracket-pair-colorizer-2.colors": [],
    "bracket-pair-colorizer-2.highlightActiveScope": true,
    "bracket-pair-colorizer-2.showBracketsInGutter": true,
    "bracket-pair-colorizer-2.showHorizontalScopeLine": false,
    "bracket-pair-colorizer-2.showVerticalScopeLine": false
```
I think it would be nice to have the option to set `"bracket-pair-colorizer-2.colors"` to `"None"` to let the extension use the current theme's colors for brackets in the gitter. Currently, brackets with no color set are shown as black text in the gutter which aren't very useful with dark themes:
![image](https://user-images.githubusercontent.com/7832163/46749778-b7b1fa80-cc73-11e8-8ee1-3ecbd023a53d.png)

**Comment by CoenraadS** [comment]
Unfortunately afaik I can't access the theme colors :(

https://github.com/Microsoft/vscode/issues/32813

**Comment by GammaGames** [comment]
Darn! Maybe a setting to set the gutter, instead? I hope they eventually add a way to get theme colors.

Thank you!

**Comment by CoenraadS** [comment]
Maybe you can just set the color to: `#dfdfbf`

**Comment by amueller** [comment]
It would be great to have some way to do something sensible on white background, though. Not sure if it's possible to detect but there's no documented way to change the colors right now (I see there is one now), but then I still need to make up a color palette. I think white background is not that uncommon.

**Comment by amueller** [comment]
I thought doing something like this would work
```
    "bracket-pair-colorizer-2.colors": [
        "editor.foreground",
        "selection.background",
        "editorCursor.background"
    ]
```
but it doesn't. Any suggestions / ideas why?

**Comment by CoenraadS** [comment]
I will look at it this weekend. Current I think I discard any non-valid css colors, but I think I should just directly apply the string and then the themes css will take over.

**Comment by amueller** [comment]
Sweet! I hard-coded colors for me now but I feel something like this could lead to a more general solution that could be mentioned in the readme or similar?

**Comment by CoenraadS** [comment]
Ok should be working in v0.27 (except for gutters)

**Comment by sastreyko** [comment]
CoenraadS
is it possible to setup gutter with the same color as theme?
