### ISSUE TITLE
When can we expect a stable release?

### ISSUE THREAD

**Issue by thevirajshelke** [CoenraadS/Bracket-Pair-Colorizer-2#243]
Your [Bracket Pair](https://github.com/CoenraadS/BracketPair) plugin is awesome and I have been using it for a long time now @CoenraadS. We all are really happy to see that you are developing this new version of the same plugin which uses the same engine as that of vscode.

I just wanted to ask you if this plugin is still in beta? If yes then when can we expect a stable release?
I wanted to shift from the old extension to this new one but I am waiting for the first stable release.

Would be glad if you let us know about the same :) Thanks a lot for this awesome extension and the previous one as well :) Looking forward for the stable release of the extension. 

All the best :+1:

**Comment by CoenraadS** [comment]
I have stopped development long time ago, so I think it's stable 😀

**Comment by thevirajshelke** [comment]
@CoenraadS, In that case, it would be really great if you would update the README.md and remove the `beta` from there. This will avoid confusion whenever someone visits the marketplace or Github repo.

I am pretty sure that you will be maintaining the codebase and will keep fixing the bugs :) 

To all the people who might disagree with removing the `beta` from the README.md and declaring the package as stable, you all need to understand that no software is bug-free, so it doesn't mean we can't call it a stable version. So even before you guys comment anything kindly take the difference into consideration. Also, keep reporting bugs if any so that it'll help developers fix as many issues as possible.

I hope @CoenraadS that you will fix & close issues whenever possible :) :+1: 

Regards & Thank You!

Note:- We can mark this issue as closed once the `beta` is removed from README.md

**Comment by CoenraadS** [comment]
I removed it, but it's not packaged in the current release. Whenever next release is the text will be gone.

**Comment by phil294** [comment]
Is there a specific reason why the master branch is two years old?
