### ISSUE TITLE
Stopped working on latest version of VS Code Insiders

### ISSUE THREAD

**Issue by sharkweek** [CoenraadS/Bracket-Pair-Colorizer-2#249]
I'm using it for some C++ development, and I noticed that after today's nightly, it stopped working. `Bracket-Pair-Colorizer` v1 seems to still work, though.

Version: 1.45.0-insider (user setup)
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T10:02:48.114Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by sellsjonathan** [comment]
Just noticed the latest release (April 2020 (version 1.45)) it's similarly broken - v1 works still.

**Comment by Davilink** [comment]
A re-install worked for me. (Uninstall, reload vscode, install)

**Comment by mattdenkers** [comment]
I just updated to VSCode 1.45.0 and lost functionality as well. I've noticed it in .js files and .vue files so far.

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by latipun7** [comment]
Bracket Pair Colorizer v1 still work on VSCode 1.45.0, and I have same issue too, this is no longer work for v2

Version: 1.45.0 (system setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by wapenshaw** [comment]
Doesn't work in ver 1.4.5 anymore. 

I reverted to v1 and that is working.

**Comment by mogzol** [comment]
This is due to a change in the vscode-textmate library. I've made a PR to fix the issue: #260
