### ISSUE TITLE
Brackets in comments are colorized if Rainbow Bracket extension is installed

### ISSUE THREAD

**Issue by alexrosano** [CoenraadS/Bracket-Pair-Colorizer-2#25]
Currently using TypeScript + Angular 6.
It would be really great if there was an option to disable the bracket coloring for comments.  Currently, brackets inside comments are colorized.  I find this to be distracting.
Example:
<img width="537" alt="comments_colored" src="https://user-images.githubusercontent.com/190205/46908712-ebe81e00-cef4-11e8-9566-f230ce76aacc.png">

Another example - code commented out inside a class.
<img width="535" alt="comments2" src="https://user-images.githubusercontent.com/190205/46908743-7466be80-cef5-11e8-81dc-75cda10bd218.png">

**Comment by alexrosano** [comment]
Actually, I think I found the culprit.  This extension causes the issue:
https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets

**Comment by alexrosano** [comment]
I have updated the ticket title to reflect my latest research.  I'd say this issue is very low priority.  I will leave it open just for posterity.

**Comment by alumni** [comment]
I have this issue and rainbow-brackets is not installed. Brackets are highlighted inside comments, and the bad part is when you have just an open bracket, but no closing bracket - it will highlight it as if it's part of the code.
