### ISSUE TITLE
Doesn't work with newer version 1.45 of Visual Studio Code

### ISSUE THREAD

**Issue by YannCoder** [CoenraadS/Bracket-Pair-Colorizer-2#261]
Doesn't work with the brand new version 1.45 of Visual Studio Code.
I uninstalled the v2 of your extension, and reinstall the v1 that work fine :-)

**Comment by FireofGods** [comment]
I have the same problem too

**Comment by MariuzM** [comment]
PR fix has been issues see previous posts. But i am curious after PR fix how long does it take to be in VSCode Marketplace?

**Comment by FireofGods** [comment]
IIRC the owner of the extension needs to release an update to the extension manually.
After he releases the update the extension will update almost instantaneously, provided you are connected to the internet that is.

**Comment by Matthew-Frazier** [comment]
> Doesn't work with the brand new version 1.45 of Visual Studio Code.
> I uninstalled the v2 of your extension, and reinstall the v1 that work fine :-)

I had tried the same thing, but I had issues with some of my .html.erb files were the brackets don't always colorize. So I just reverted back to 1.44 of VScode.

**Comment by mogzol** [comment]
Yeah this should be fixed by PR #260. We just have to wait for @CoenraadS to review that and then create the new release.

**Comment by CoenraadS** [comment]
fixrd
