### ISSUE TITLE
Extension stopped colorizing after an update

### ISSUE THREAD

**Issue by pzmarzly** [CoenraadS/Bracket-Pair-Colorizer-2#263]
Using Codium (open source build of VS Code). Updating to 0.1.1 broke colorizing. Using default extension settings.

Before, few seconds after Codium started, the extension started colorizing. It doesn't do that anymore.

![Screenshot from 2020-05-08 22-21-55](https://user-images.githubusercontent.com/8074163/81446107-84e72580-917a-11ea-8689-b473432c0810.png)

```bash
$ codium --version
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
```

Downgrading to 0.0.29 for now: `codium --install-extension CoenraadS.bracket-pair-colorizer-2@0.0.29`.

**Comment by CoenraadS** [comment]
If you update codium to v1.45 the new extension should work.

**Comment by pzmarzly** [comment]
Indeed, on `codium v1.45` older version 0.0.29 doesn't work, while newer 0.1.1 does. It's a shame that forward/backward compatibility has been broken here, but now that I look at [vscode API docs](https://code.visualstudio.com/api/references/vscode-api), I also don't see any method to check for VS Code version.
