### ISSUE TITLE
Feature Request: Indent-Rainbow Style Support

### ISSUE THREAD

**Issue by JustinGrote** [CoenraadS/Bracket-Pair-Colorizer-2#277]
I love indent rainbow, but the problem is that the colors don't sync with bracket pair colorizer. I can customize them but they're based on indentation not by bracket depth, so if I for instance do two brackets on a single level it will throw it off.

Would it be possible to add this kind of indentation highlighting to Bracket pair colorizer that would be aware of the brackets so the colors would match the brackets?

![image](https://user-images.githubusercontent.com/15258962/82689514-71729a80-9c0f-11ea-8064-085379ca2291.png)

**Comment by DrakoPOD** [comment]
You just need to change the config for the extension, Bracket or Ident, in this case, I change Indent configuration in `settings.json`:
```json
    "indentRainbow.colors": [
        "rgba(255, 215, 0, 0.07)",
        "rgba(218, 112, 214, 0.07)",
        "rgba(135, 206, 250, 0.07)"
    ]
```

**Comment by JustinGrote** [comment]
I've since made this change, complete forgot this issue was still open. Thanks though!
