### ISSUE TITLE
Spam in Debug Console when running Extension Host for unrelated extension dev

### ISSUE THREAD

**Issue by justarandomgeek** [CoenraadS/Bracket-Pair-Colorizer-2#288]
While running Extension Host for debugging my own extension, the debug console is spammed with these: 
![image](https://user-images.githubusercontent.com/5246445/84278735-1e4f8180-ab03-11ea-91df-a5437427a4ff.png)

**Comment by boltex** [comment]
Can confirm., I'm developing vscode extensions and I disabled bpc2 until this is fixed ! 
(great extension nonetheless i hope you fix this soon!)  :)

**Comment by CoenraadS** [comment]
fixed
