### ISSUE TITLE
stop working on 1.46.0 vscode update

### ISSUE THREAD

**Issue by JorgeDLG** [CoenraadS/Bracket-Pair-Colorizer-2#289]
The extension works well before this update.

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.15-arch1-1

**Comment by MediumBrownToast** [comment]
Mine stopped working in the April update.

I don't know why I didn't try this earlier, but I disabled the extension, reloaded VS Code and enabled it again and it is working again :)

**Comment by JorgeDLG** [comment]
> Mine stopped working in the April update.
> 
> I don't know why I didn't try this earlier, but I disabled the extension, reloaded VS Code and enabled it again and it is working again :)

Yes this works. thx!
