### ISSUE TITLE
problem while using jQuery in html

### ISSUE THREAD

**Issue by patel33hardik** [CoenraadS/Bracket-Pair-Colorizer-2#32]
![image](https://user-images.githubusercontent.com/44590578/48173625-450a6c80-e350-11e8-81db-f6afe8db47d6.png)

If I used jquery in HTML page it considers > and < as bracket, not arithmetic oprators.

**Comment by pr-yemibedu** [comment]
Hello,
 Is this wrapped in a pair of `<script type="text/javascript">` and `</script>` tags? Just wondering where the cross over between rendering HTML and **something else** occurs. Thank you. Good day.

**Comment by CoenraadS** [comment]
I disabled `<>` globally for now
