### ISSUE TITLE
Not all the brackets wanted being colorized

### ISSUE THREAD

**Issue by GiacomoZheng** [CoenraadS/Bracket-Pair-Colorizer-2#35]
When I was adjusting my language, I find that this extension would colorize all the brackets added in the `brackets` object of `language-configuration.json`, like
![image](https://user-images.githubusercontent.com/35882458/48256386-59cb2b00-e44a-11e8-9717-1958bca785af.png)
(This is `java`),

and this setting can help us to keep same the indent.

@CoenraadS 
**The problem is that, I don't want to colorize everything in the `brackets`, as I may just want it to keep the indent.**

This is the configuration of my language, and I don't want to colorize the `@` and `■` pair.

![default](https://user-images.githubusercontent.com/35882458/48256667-479dbc80-e44b-11e8-9474-842080eec5b8.png)

I think one more setting can be added to deal with this problem.

Thanks.

**Comment by pr-yemibedu** [comment]
Hello,
 So you would like a setting to list either the index of or the found sets of brackets to ignore? Like:
  - `brackets.ignore: {0, 2}`
  - `brackets.ignore: {["@","#"],["!", "|"]}`

This would then ignore these across every file. Would this be allowed to have filters?
  - `brackets.ignore: {extension:".cs", 0, 2}`
  - `brackets.ignore: {language:"java", ["@","#"],["!", "|"]}`

Cool notion of having the custom handling. Also were you asking to ignore all features (margin note and scope highlight) or just the color part? Thank you. Good day.

**Comment by pr-yemibedu** [comment]
Similar to #28 asking for more Sublime ability.

**Comment by GiacomoZheng** [comment]
I think it is a good idea to add such a setting.

For me, if I want to ignore it, I won't regard it as a pair of brackets anymore. It is, I prefer to ignore all the features.

By the way, in fact, after I try to colorize the `@` and `■`, I think it is a good idea to colorize them. ………

One more thing, if it is possible to add a setting as,
``` json
"[java]": {
    "bracket-pair-colorizer-2.ignore": { [ "@", "#" ], [ "!", "|" ] }
}
```

I find that for my `settings.json`, only some setting like `editor.*` is allowed.
