### ISSUE TITLE
Make it look like BPC1?

### ISSUE THREAD

**Issue by GammaGames** [CoenraadS/Bracket-Pair-Colorizer-2#4]
I have the following settings for BPC1:
![image](https://user-images.githubusercontent.com/7832163/45606086-6eb5b000-b9ff-11e8-8b47-79efd4d11e29.png)

It makes the brackets different shades of white, which looks nice with my theme. When I try to move the settings over to BPC2 though, it looks like:

![image](https://user-images.githubusercontent.com/7832163/45606140-cf44ed00-b9ff-11e8-947f-0c89658042f6.png)

It's not showing it in the gutter and the colors aren't right. For now I'll just keep using the first extension, because that works for the most part.

**Comment by CoenraadS** [comment]
Thanks for your feedback, however I could not reproduce your issue.

![image](https://user-images.githubusercontent.com/5593825/45633786-ff909800-baa0-11e8-8fe4-22ac54b62d11.png)


I have some issues coloring files inside the ./vscode folder, could you check how it operates on other files?

**Comment by GammaGames** [comment]
![image](https://user-images.githubusercontent.com/7832163/45635082-4ced1500-ba61-11e8-9905-137fdb6f9655.png)
Mine isn't colored, and they're not showing in the gutter.

Here's my newest settings:

```json
    "bracket-pair-colorizer-2.colorMode": "Consecutive",
    "bracket-pair-colorizer-2.colors": [
        "#fff",
        "#e0e0e0",
        "#a3a3a3",
        "#858585"
    ],
    "bracket-pair-colorizer-2.forceIterationColorCycle": true,
    "bracket-pair-colorizer-2.forceUniqueOpeningColor": true,
    "bracket-pair-colorizer-2.highlightActiveScope": false,
    "bracket-pair-colorizer-2.showBracketsInGutter": true,
    "bracket-pair-colorizer-2.showHorizontalScopeLine": false,
    "bracket-pair-colorizer-2.showVerticalScopeLine": false,
```

**Comment by CoenraadS** [comment]
Hmm this is very strange. I tried with your settings and still works:

Language: Javascript

![image](https://user-images.githubusercontent.com/5593825/45643502-86eb0500-babb-11e8-98a9-4932e9cfefab.png)

VSCode v1.27.2, BC2 v0.0.9

**Comment by CoenraadS** [comment]
With v0.0.10 the changes should reflect directly onto the settings file after saving. Feel free to reopen if it still occurs.
