### ISSUE TITLE
Jinja2 issue with closing braket

### ISSUE THREAD

**Issue by IainVM** [CoenraadS/Bracket-Pair-Colorizer-2#40]
Language: Jinja

Screenshot:
![image](https://user-images.githubusercontent.com/2806167/49161958-d05c9980-f321-11e8-82cb-c71fba331db4.png)

Copy/Pastable example:
```jinja
test
{{ tfstate.version }}
{% block group %}
```

**Comment by CoenraadS** [comment]
Should be fixed in v0.0.25
