### ISSUE TITLE
Support for svelte-vscode

### ISSUE THREAD

**Issue by anirudh242** [CoenraadS/Bracket-Pair-Colorizer-2#436]
The extension does not work on svelte files.

Image-
![image](https://user-images.githubusercontent.com/73819495/115826357-667c4780-a428-11eb-84f8-e9e5567324f7.png)

Copy pastable example-
```
<script lang="ts">
  let todoName: string;
  $: todos = [];
  let isStrike: boolean;
  let oldTodos: any[];

  function todoSubmit() {
    todos = [...todos, todoName];
    oldTodos = [...todos];
    todoName = '';
    console.log(todos);
  }

  function todoStrike(index) {
    if (isStrike) {
      isStrike = false;
      todos[index] = oldTodos[index];
    } else {
      isStrike = true;
      oldTodos = [...todos];
      todos[index] = todos[index].strike();
    }
  }

  function todoRemove(index) {
    todos.splice(index, 1);
    todos = [...todos];
    console.log(todos);
  }
</script>
```

**Comment by microdou** [comment]
It works for me. `.svelte` file is supported.

However, looks like it only work in local environment. Colorization of  `.svelte`  file doesn't work in remote containers.

See https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/262

**Comment by anirudh242** [comment]
Bracket pair colorizer 2 is now deprecated.
