### ISSUE TITLE
Bracket Pair Colorizer Colors To Native VSCode

### ISSUE THREAD

**Issue by tomassasovsky** [CoenraadS/Bracket-Pair-Colorizer-2#483]
I'm very used to the colors in this extension and want to keep using the exact same ones. What do I need in my settings.json file to do that?

**Comment by anirudh242** [comment]
In your settings.json file try replacing the default colors with the extensions colors like this (The colors I've given are not the same ones as the extension): 
```json
"workbench.colorCustomizations": {
    "editorBracketHighlight.foreground1": "#5bb3b3",
    "editorBracketHighlight.foreground2": "#fac863",
    "editorBracketHighlight.foreground3": "#f99157",
    "editorBracketHighlight.foreground4": "#ec5f67",
    "editorBracketHighlight.foreground5": "#bb80b3",
    "editorBracketHighlight.foreground6": "#98C379",
}
```

**Comment by tomassasovsky** [comment]
Thanks for that and for one of the best, most useful extensions I've ever used!
