### ISSUE TITLE
The algori

### ISSUE THREAD

**Issue by seyedAliHamedi** [CoenraadS/Bracket-Pair-Colorizer-2#490]
Hi, this is not an actual issu i just wanted a way to communicate with the authors
I have a university assignment and it requires an algorithm to match brackets with each other i just wanted to have an explanation to how it done in this project(bracket pair colorizer) if it's possible
BTW thanks for the great extension and the work you've done guys😁

**Comment by gusbemacbe** [comment]
@seyedAliHamedi

@CoenraadS will no longer update this extension. You must contact the Microsoft's new owners of his extension:

https://github.com/microsoft/vscode/issues/136475
