### ISSUE TITLE
How to use both Colorizer and Colorizer-2?

### ISSUE THREAD

**Issue by klukiyan** [CoenraadS/Bracket-Pair-Colorizer-2#50]
1. When writing Javascript in Laravel Blade's *.blade.php files, only Bracket Pair Colorizer **2** does color Javascript's brackets. The first one only colors HTML. 
2. When writing SQL/MSSQL queries in *.sql files - Bracket Pair Colorizer 1 does color the brackets, while the Bracket Pair Colorizer **2** does **NOT**.
_Thus, I'm asking for a potential solution._
Is there any way I could make Bracket Pair Colorizer 1 to be active when I write in ***.sql** and Bracket Pair Colorizer 2 when I write in all other languages?
How to achieve it?

**Comment by CoenraadS** [comment]
I'm not sure how to run both at the same time but I can help enable SQL for now.

To fix SQL bracket highlighting with v2, you can edit a file to enable it.

`%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.4.0\syntaxes\sql.configuration.json`

```
{
	"comments": {
		"lineComment": "--",
		"blockComment": [ "/*", "*/" ]
	},
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"]
	]
}
```

**Comment by klukiyan** [comment]
@CoenraadS , thank you. It did the magic. Now I can enjoy the bracket pair colorizer 2 SQL. Sincerely thank you!
