### ISSUE TITLE
Reasoning for seperate repo for v2?

### ISSUE THREAD

**Issue by peterschussheim** [CoenraadS/Bracket-Pair-Colorizer-2#6]
Please include the language you are using, a screenshot, and copy/pastable example.Hi,

Great extension! 👍   Just was curious if there were specific reasons why v2 is aseparatee repo.

**Comment by CoenraadS** [comment]
Good question, I will add it to the readme.

- Why create a version 2, and not continue the old extension?
    - Version 2 contains a new parsing engine which should be more accurate and enable more flexibility. However as a result there are many breaking changes to the settings, and also the current language support is very limited, although I hope to grow it quickly.

**Comment by peterschussheim** [comment]
thanks for the response!
