### ISSUE TITLE
opacity property doesn't accept decimal value

### ISSUE THREAD

**Issue by PixelT** [CoenraadS/Bracket-Pair-Colorizer-2#67]
Earlier it works OK, it seems to stop working after last update? 
```    
"bracket-pair-colorizer-2.activeScopeCSS": [
        "backgroundColor : {color}; opacity: 0.5",
        "outline : true"
]
```

**Comment by CoenraadS** [comment]
Try putting it on a new line:

"bracket-pair-colorizer-2.activeScopeCSS": [
        "backgroundColor : {color};",
         "opacity: 0.5",
        "outline : true"
]
