### ISSUE TITLE
Support for Html Tag

### ISSUE THREAD

**Issue by saileshkush95** [CoenraadS/Bracket-Pair-Colorizer-2#68]
Please add for supporting HTML tags.   This will help to identify opening and closing tag easily. Thanks for this amazing plugins

**Comment by zygama** [comment]
I'd really like to see the scopeline option for HTML/JSX tags ! Thank you for your work anyway :)

**Comment by xenophilicibex** [comment]
I'm holding off on updating to 2 until HTML/JSX are supported :) Love the project!
