### ISSUE TITLE
How to define bracket pair color based on bracket type

### ISSUE THREAD

**Issue by pingshunhuangalex** [CoenraadS/Bracket-Pair-Colorizer-2#88]
The old bracket pair has this amazing "bracketPairColorizer.independentPairColors" where you can define colour based on the bracket type. However, somehow this is not available in the new version. Some help here would be nice as all I get is lots of colours on the screen...

**Comment by el3gy** [comment]
`"bracket-pair-colorizer-2.colorMode": "Independent"` will at least cycle through the color list independently for each type of bracket, but I think you're asking for the ability to define separate color lists for each type.

And if _you_ aren't, _I_ am. (Definitely an `enhancement`, though)
