### ISSUE TITLE
Lines under brackets don't seem to be updating properly

### ISSUE THREAD

**Issue by bryangingechen** [CoenraadS/Bracket-Pair-Colorizer-2#9]
Try pasting the following into e.g. `test.js` and then typing or adding spaces or deleting stuff in between any of the brackets in the second line. The colored lines which connect opening and closing brackets don't update as you type.
```
a(a) {b} a(c) {d}
a(a) {b} a(c) {d}
```
Whatever's causing this seems to be causing some other issues as well, but this was the quickest minimal example of bad behavior I was able to cook up.

**Comment by CoenraadS** [comment]
Thanks so much for being an early tester. I released v0.0.11 which hopefully finally has correct behaviour

**Comment by bryangingechen** [comment]
No problem, thanks for the quick response! Let me know if there's anything in particular you need extra testing on. I haven't dug into it your extension code yet, but I'd be happy to try to help if there's something specific you want extra eyes on.

**Comment by CoenraadS** [comment]
v0.0.18 contains a ton of coloring fixes, hopefully they are resolved now

**Comment by bryangingechen** [comment]
I noticed you removed the LANGUAGE_SUPPORT file. What's the way of writing new language support in the new version? The language I was using (the [Lean theorem proving language](https://github.com/leanprover/lean/)) and [my fork of its official VS code extension (which adds bracket support)](https://github.com/leanprover/vscode-lean/pull/90) no longer work.

**Comment by CoenraadS** [comment]
Bracket support is now read from `language-configuration.json` which can be defined by a language extension. https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

**Comment by bryangingechen** [comment]
Hmm, the extension does provide [language-configuration.json](https://github.com/leanprover/vscode-lean/blob/master/language-configuration.json); any idea what I need to change to get it to work?

**Comment by CoenraadS** [comment]
Probably its broken on my side then. I'll look at it tonight

**Comment by CoenraadS** [comment]
@bryangingechen The file had comments in it, making it invalid json and crashing my parser. I switched to JSON5 ins v 0.0.20 and now it should be working

**Comment by bryangingechen** [comment]
Great, thanks so much!
